### PR TITLE
Update master with v9.0.2 tag

### PR DESCRIPTION
**Pull request by jentfoo**
This merges the upstream `v9.0.2` tag into `master`.  The added merge commit is to resolve the conflicts in `redis.go`.  There were two notable conflicts:
1. clientName added logic needed to be handled: https://github.com/gravitational/redis/commit/a872c35b1a9cbd19904010c105281ad15ab687ab
2. I accepted the upstream changes for `releaseConn` logic: https://github.com/gravitational/redis/commit/21e1954745a12948de5ccdea9f6b335fe169a463 (replacing our commit here: https://github.com/gravitational/redis/commit/d5ec4a6b60033f41606b62a91cf96a63e8523e6b)

### CODE REVIEW

**Comment by greedy52** [comment]
you want this patch for the building error
```
diff --git a/proto.go b/proto.go
index 9b788c8..d942290 100644
--- a/proto.go
+++ b/proto.go
@@ -4,7 +4,7 @@ import (
        "bytes"
        "io"
 
-       "github.com/go-redis/redis/v9/internal/proto"
+       "github.com/redis/go-redis/v9/internal/proto"
 )
 
 type Reader = proto.Reader
```

however, seems test still fails. maybe we broke something

**Comment by jentfoo** [comment]
Thank you @greedy52, I had already pushed that update.  It does look like additional changes will be needed to get this working.

No worries, I will iterate on it as I am able to and transition this PR off a Draft once it's ready for review

**Comment by jentfoo** [comment]
Discussed with @greedy52 in DM.  We had to revert one of our changes to allow the tests to pass in the cleanest fashion.  We may need to re-apply this fix (if it was not fixed by other means): https://github.com/gravitational/redis/commit/8ff76d53bb016e2560c5f6cb673f3496c96f30b5

I believe this PR is good to review in its current state.  @greedy52 can you help in verifying this update?

**Comment by greedy52** [comment]
I will open this PR (the rework of the above rolled-back commit) after this one is merged
https://github.com/gravitational/redis/pull/37/files

On the Teleport side, has to update the import path:
https://github.com/gravitational/teleport/pull/22738/files
All db tests passed with the exception of `TestReadWriteStatus` which should pass once the rework fix is in.

**Review by greedy52 — APPROVED** [review]

**Comment by jentfoo** [comment]
Thank you @greedy52!

**Pull request merged**
