### PR TITLE
Merge Teleport.3 tag into master

### PR DESCRIPTION
**Pull request by jentfoo**
This tag is currently referenced by teleport: https://github.com/gravitational/teleport/blob/master/go.mod#L368

But is not current with `master` (or any other branch).  This PR is to merge these changes into master so that we can perform future updates.

### CODE REVIEW

**Comment by jentfoo** [comment]
Only changes in this PR are the inclusion of CodeQL and Dependency-Review jobs from `master`: https://github.com/gravitational/redis/compare/v9.0.0-teleport.3...gravitational:redis:teleport.3

Although some jobs are failing I believe we should merge this change as is and fix the remaining jobs in a follow up PR to update this repo.

Let me know your thoughts @smallinsky and @greedy52, thank you!

**Comment by jentfoo** [comment]
It's unclear why the build is not working here when it did in #33.

I still suggest we merge this in the current condition since it's as close to the `teleport.3` tag as possible.  We can address the build failures in the next PR when we update to v9.0.2

**Comment by greedy52** [comment]
@jentfoo thanks for looking into this

[v9.0.0-teleport.3](https://github.com/gravitational/redis/releases/tag/v9.0.0-teleport.3) is released from branch [release/v9.0.0-rc.1](https://github.com/gravitational/redis/tree/release/v9.0.0-rc.1)

Personally, I felt our initial strategy of doing our custom changes on master and release there didn't work very well as it's very hard to sync changes. So I cherry-picked Teleport changes and put them on top of the official release tag [v9.0.0-rc.1](https://github.com/redis/go-redis/tree/v9.0.0-rc.1).

What's our general approach to maintaining forks?

**Comment by jentfoo** [comment]
@greedy52 and myself discussed this some in DM.  We discussed if we want to continue to use `master`, or switch to `teleport` for our active branch like some other repo's.  We arrived at continuing to use `master` for now.  So I will merge this PR and follow it up with another one to update with `9.0.2`.

**Review by greedy52 — APPROVED** [review]

**Pull request merged**
